"""Add strain and bio age

Revision ID: 6854998a00a0
Revises: 79f91c8e2fbe
Create Date: 2026-05-27 14:44:38.760905

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6854998a00a0'
down_revision: Union[str, Sequence[str], None] = '79f91c8e2fbe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_health', sa.Column('strain_score_app', sa.Float(), nullable=True))
    op.add_column('fitness_estimates', sa.Column('biological_age_app', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fitness_estimates', 'biological_age_app')
    op.drop_column('daily_health', 'strain_score_app')
    # ### end Alembic commands ###
