"""create_goals_table

Revision ID: df6b55ff299b
Revises: 6854998a00a0
Create Date: 2026-05-29 11:49:01.535711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df6b55ff299b'
down_revision: Union[str, Sequence[str], None] = '6854998a00a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goals',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('goal_description', sa.Text(), nullable=True),
    sa.Column('goal_race_name', sa.String(length=255), nullable=True),
    sa.Column('goal_race_date', sa.Date(), nullable=True),
    sa.Column('goal_target_time', sa.String(length=20), nullable=True),
    sa.Column('weekly_training_hours', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    # Data migration: Copy existing user goals to the new goals table
    bind = op.get_bind()
    bind.execute(sa.text("""
        INSERT INTO goals (id, user_id, goal_description, goal_race_name, goal_race_date, goal_target_time, weekly_training_hours, is_active, created_at, updated_at)
        SELECT 
            gen_random_uuid(),
            id, 
            goal_description, 
            goal_race_name, 
            goal_race_date, 
            goal_target_time, 
            weekly_training_hours, 
            TRUE, 
            NOW(), 
            NOW()
        FROM users
        WHERE goal_description IS NOT NULL 
           OR goal_race_name IS NOT NULL 
           OR goal_race_date IS NOT NULL 
           OR goal_target_time IS NOT NULL
           OR weekly_training_hours IS NOT NULL
    """))

    op.drop_column('users', 'goal_description')
    op.drop_column('users', 'goal_race_name')
    op.drop_column('users', 'weekly_training_hours')
    op.drop_column('users', 'goal_race_date')
    op.drop_column('users', 'goal_target_time')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('goal_target_time', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('goal_race_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('weekly_training_hours', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('goal_race_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('goal_description', sa.TEXT(), autoincrement=False, nullable=True))

    # Data migration: Copy goals back to users table before dropping goals table
    bind = op.get_bind()
    bind.execute(sa.text("""
        UPDATE users
        SET 
            goal_description = g.goal_description,
            goal_race_name = g.goal_race_name,
            goal_race_date = g.goal_race_date,
            goal_target_time = g.goal_target_time,
            weekly_training_hours = g.weekly_training_hours
        FROM (
            SELECT DISTINCT ON (user_id) 
                user_id, goal_description, goal_race_name, goal_race_date, goal_target_time, weekly_training_hours
            FROM goals
            ORDER BY user_id, is_active DESC, updated_at DESC
        ) g
        WHERE users.id = g.user_id
    """))

    op.drop_table('goals')
    # ### end Alembic commands ###
